/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_settings_broadcast_KillFileBroadCast */

#ifndef _Included_com_android_internal_policy_impl_PhoneWindowManager
#define _Included_com_android_internal_policy_impl_PhoneWindowManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_settings_broadcast_KillFileBroadCast
 * Method:    killaction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_internal_policy_impl_PhoneWindowManager_killaction
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
