/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_philips_switchspk_SwitchSpk */

#ifndef _Included_com_philips_switchspk_SwitchSpk
#define _Included_com_philips_switchspk_SwitchSpk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_philips_switchspk_SwitchSpk
 * Method:    setSpk_native
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_sps_switchspk_SwitchSpk_setSpk_1native
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
