/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_settings_broadcast_KillFileBroadCast */

#ifndef _Included_com_jwd_carboy_voice_service_JwdVoiceService
#define _Included_com_jwd_carboy_voice_service_JwdVoiceService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_settings_broadcast_KillFileBroadCast
 * Method:    getSystemValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jwd_carboy_voice_service_JwdVoiceService_getSystemValue
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
