/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vc_carboy_SpeechVC */

#ifndef _Included_com_vc_carboy_SpeechVC
#define _Included_com_vc_carboy_SpeechVC
#ifdef __cplusplus
extern "C" {
#endif
#undef com_vc_carboy_SpeechVC_DBGI
#define com_vc_carboy_SpeechVC_DBGI 1L
#undef com_vc_carboy_SpeechVC_DBGE
#define com_vc_carboy_SpeechVC_DBGE 1L
/*
 * Class:     com_vc_carboy_SpeechVC
 * Method:    _native_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vc_carboy_SpeechVC__1native_1init
  (JNIEnv *, jobject);

/*
 * Class:     com_vc_carboy_SpeechVC
 * Method:    _initVC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_vc_carboy_SpeechVC__1initVC
  (JNIEnv *, jobject);

/*
 * Class:     com_vc_carboy_SpeechVC
 * Method:    _getVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_vc_carboy_SpeechVC__1getVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_vc_carboy_SpeechVC
 * Method:    _setWorkMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_vc_carboy_SpeechVC__1setWorkMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_vc_carboy_SpeechVC
 * Method:    _getWorkMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_vc_carboy_SpeechVC__1getWorkMode
  (JNIEnv *, jobject);

/*
 * Class:     com_vc_carboy_SpeechVC
 * Method:    _setFuncMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_vc_carboy_SpeechVC__1setFuncMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_vc_carboy_SpeechVC
 * Method:    _getFuncMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_vc_carboy_SpeechVC__1getFuncMode
  (JNIEnv *, jobject);

/*
 * Class:     com_vc_carboy_SpeechVC
 * Method:    _setDACGain
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_vc_carboy_SpeechVC__1setDACGain
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_vc_carboy_SpeechVC
 * Method:    _setWakeupID
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_vc_carboy_SpeechVC__1setWakeupID
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_vc_carboy_SpeechVC
 * Method:    _startWakeup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_vc_carboy_SpeechVC__1startWakeup
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
