/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_settings_broadcast_KillFileBroadCast */

#ifndef _Included_com_jwd_fv200_nx300_VoiceInterfaceJni
#define _Included_com_jwd_fv200_nx300_VoiceInterfaceJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_settings_broadcast_KillFileBroadCast
 * Method:    getSystemValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_com_jwd_fv200_nx300_VoiceInterfaceJni_voicePropertiesSet
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
